/// AST Definition types (autogenerated by `generate-ast`)
use crate::lexer::Token;

#[derive(Debug, Copy, Clone)]
pub struct Object {}

#[derive(Debug, Clone)]
pub enum Expr<'a> {
    Binary {
        left: &'a Expr<'a>,
        operator: Token,
        right: &'a Expr<'a>,
    },
    Grouping {
        expression: &'a Expr<'a>,
    },
    Literal {
        value: Object,
    },
    Unary {
        operator: Token,
        right: &'a Expr<'a>,
    },
}
